version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    #- ./data/1.0/1_users.sql:/docker-entrypoint-initdb.d/1_users.sql 
    - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    container_name: cache
    command: redis-server --requirepass "mysecretredispassword"
    # environment:
    #   REDIS_PASSWORD: mysecretredispassword
    ports:
     - 6379:6379
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha39
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key": "e4f05996bffbe1fd0d1dd52dae6fec5dde3bafff4eed4064ba515cfaf3fabee905e36f3a44de129600bab880a21043ef6c21866d21d9440bc41a4325cb29405c"}'
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey #required if HASURA_GRAPHQL_JWT_SECRET specified
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  db_data:
