// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ninshoo_hasura

type AuthPayload struct {
	Token string `json:"token"`
}

type Instructions struct {
	Text string `json:"text"`
}
