app-name = "gqlgen-starter"
version = 1.0

[db]
host = "localhost"
port = "5433"
user = "postgres-dev"
password = "s3cr3tp4ssw0rd"
dbname = "dev"

[log]
debug-mode = true
log-format = "%{color}%{time:2006/01/02 15:04:05 -07:00 MST} [%{level:.6s}] %{shortfile} : %{color:reset}%{message}"