app-name = "glqgen-todos-auth"
version = 1.0

[db]
host = "localhost"
port = "5433"
user = "postgres-dev"
password = "s3cr3tp4ssw0rd"
dbname = "dev"


[auth]
#jwt sign secret
jwt-secret = "1234"
#jwt expired time in second
jwt-expire-in = "40000s"

[log]
debug-mode = true
log-format = "%{color}%{time:2006/01/02 15:04:05 -07:00 MST} [%{level:.6s}] %{shortfile} : %{color:reset}%{message}"

[deeplinker]
androidPackageName = "home.sacha.firebasetest"
domainURIPrefix= "https://minorys.page.link"
confirmationEndpoint ="https://ecstatic-heisenberg-ea2789.netlify.com/confirmation"
resetPasswordEndpoint ="https://ecstatic-heisenberg-ea2789.netlify.com/reset"

[tokenizer]
redis-url="localhost:6379"
password=""

[smtp]
identity = ""
username = "apikey"
host="smtp.sendgrid.net"
address="smtp.sendgrid.net:25"