version: '3'
services:

  # auth:
  #   build:
  #     context: ./auth
  #   volumes:
  #     - ./auth:/go/src/github.com/user/Sach97/api
  #   links:
  #     #- postgres
  #     - redis
  #   networks:
  #     - auth-network
  #   environment:
  #   - REDIS_URL=redis://cache

  postgres:
    image : postgres
    volumes:
      - /psqldata:/var/lib/postgresql/data
      - ./data/1.0/1_users.sql:/docker-entrypoint-initdb.d/1_usrs.sql 
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
      PGDATA: /pgdata
    ports:
      - 5433:5432
  redis:
    image: redis
    container_name: cache
    ports:
     - 6379:6379

networks:
  auth-network: