// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen_todos_auth

type AuthPayload struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type Instructions struct {
	Text string `json:"text"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}
