app-name = "glqgen-todos-auth"
version = 1.0

[db]
host = "localhost"
port = "5432"
user = "postgres"
password = "postgres"
dbname = "postgres"


[auth]
#jwt sign secret
jwt-secret = "e4f05996bffbe1fd0d1dd52dae6fec5dde3bafff4eed4064ba515cfaf3fabee905e36f3a44de129600bab880a21043ef6c21866d21d9440bc41a4325cb29405c" #length must be more than 32 for hasura
#jwt expired time in second
jwt-expire-in = "40000s"

[log]
debug-mode = true
log-format = "%{color}%{time:2006/01/02 15:04:05 -07:00 MST} [%{level:.6s}] %{shortfile} : %{color:reset}%{message}"

[deeplinker]
androidPackageName = "home.sacha.firebasetest"
domainURIPrefix= "https://minorys.page.link"
confirmationEndpoint ="https://ecstatic-heisenberg-ea2789.netlify.com/confirmation"
resetPasswordEndpoint ="https://ecstatic-heisenberg-ea2789.netlify.com/reset"

[tokenizer]
redis-url="localhost:6379"
password=""

[smtp]
identity = ""
username = "apikey"
host="smtp.sendgrid.net"
address="smtp.sendgrid.net:25"